dist: trusty
sudo: required


language: node_js

node_js:
  - "stable"

install:
  - npm install

script:
  - npm run coverage -- --coverage
  - npm run build

addons:
  sonarcloud:
    organization: "rodriguesl3-github"
  token:
    secure: ${SONAR_TOKEN}

jdk:
  - oraclejdk8

after_script:
  - sonar-scanner -X

deploy:
  provider: surge
  skip_cleanup: true
  domain: spotify-react-redux.surge.sh
  project: ./build/
on:
  all_branches: true