dist: trusty
sudo: required


language: node_js
node_js:
  - "stable"

sscript:
  - npm run coverage -- --coverage # Include coverage when running tests
  - npm run build

addons:
  sonarcloud:
    organization: "rodriguesl3-github"
  token:
    secure: ${SONAR_TOKEN}

jdk:
  - oraclejdk8

script:
  - sonar-scanner -X
  
deploy:
  provider: surge
  skip_cleanup: true
  domain: spotify-react-redux.surge.sh
  project: ./build/
on:
  all_branches: true