dist: trusty
sudo: required


language: node_js
node_js:
  - "stable"

script:
  - npm run coverage -- --coverage
  - npm run build

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls

addons:
  sonarcloud:
    organization: "rodriguesl3-github"
  token:
    secure: ${SONAR_TOKEN}

jdk:
  - oraclejdk8

script:
  - sonar-scanner -X
deploy:
  provider: surge
  skip_cleanup: true
  domain: spotify-react-redux.surge.sh
  project: ./build/
on:
  all_branches: true