language: node_js
node_js:
  - "stable"

script:
  - npm run build

addons:
  sonarcloud:
    organization: "rodriguesl3-github"
deploy:
  provider: surge
  skip_cleanup: true
  domain: spotify-react-redux.surge.sh
  project: ./build/
on:
  all_branches: true