const searchList = {
  "data": {
    "artists": {
      "href": "https://api.spotify.com/v1/search?query=emicida&type=artist&market=BR&offset=0&limit=10",
      "items": [{
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
          },
          "followers": {
            "href": null,
            "total": 1271359
          },
          "genres": [
            "brazilian hip hop",
            "brazilian reggae",
            "brazilian rock",
            "hip hop tuga",
            "mangue bit"
          ],
          "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
          "id": "2d9LRvQJnAXRijqIJDDs2K",
          "images": [{
              "height": 640,
              "url": "https://i.scdn.co/image/a320810b7abb77f7a384a415538938546f06b5bd",
              "width": 640
            },
            {
              "height": 320,
              "url": "https://i.scdn.co/image/da3bf159a2f1b9157e2027a78229e2c527bd77ad",
              "width": 320
            },
            {
              "height": 160,
              "url": "https://i.scdn.co/image/c94cd49b68550592d2e198af1ed82f1684bd4dcc",
              "width": 160
            }
          ],
          "name": "Emicida",
          "popularity": 64,
          "type": "artist",
          "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/3KYRu6Pqd8BFTM6imvX9Y0"
          },
          "followers": {
            "href": null,
            "total": 81
          },
          "genres": [],
          "href": "https://api.spotify.com/v1/artists/3KYRu6Pqd8BFTM6imvX9Y0",
          "id": "3KYRu6Pqd8BFTM6imvX9Y0",
          "images": [{
              "height": 640,
              "url": "https://i.scdn.co/image/d11a34d81ced100cf1b50db502969ddfe0eeaaa2",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/06cd2b840664ae33f2793e9b881a65f2d7f89831",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/21d349bf24413b9e9431f7c10920466d4ab4036c",
              "width": 64
            }
          ],
          "name": "Emicida",
          "popularity": 27,
          "type": "artist",
          "uri": "spotify:artist:3KYRu6Pqd8BFTM6imvX9Y0"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/2t4OkoFtc36pwt9SgDQvqO"
          },
          "followers": {
            "href": null,
            "total": 528
          },
          "genres": [],
          "href": "https://api.spotify.com/v1/artists/2t4OkoFtc36pwt9SgDQvqO",
          "id": "2t4OkoFtc36pwt9SgDQvqO",
          "images": [],
          "name": "Jorge Aragão, Zeca Pagodinho, Elza Soares, Diogo Nogueira, Emicida, Luciana Mello, Sandra de Sá, Joyce Cândido, Luciana Mello, Martinho da Vila, Vander Lee, Anitta, Xande de Pilares, Péricles, Fundo de Quintal, Maria Rita, Lenine, Alcione, Luiz Melodia, Baby do Brasil, Thais Macedo, Ivan Lins, Jorge Vercillo, Seu Jorge & Beth Carvalho",
          "popularity": 8,
          "type": "artist",
          "uri": "spotify:artist:2t4OkoFtc36pwt9SgDQvqO"
        },
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/5ncxnOGYpaa4fVqwUSypms"
          },
          "followers": {
            "href": null,
            "total": 153
          },
          "genres": [],
          "href": "https://api.spotify.com/v1/artists/5ncxnOGYpaa4fVqwUSypms",
          "id": "5ncxnOGYpaa4fVqwUSypms",
          "images": [],
          "name": "Emicida & Dj Hum",
          "popularity": 1,
          "type": "artist",
          "uri": "spotify:artist:5ncxnOGYpaa4fVqwUSypms"
        }
      ],
      "limit": 10,
      "next": null,
      "offset": 0,
      "previous": null,
      "total": 4
    },
    "tracks": {
      "href": "https://api.spotify.com/v1/search?query=emicida&type=track&market=BR&offset=0&limit=10",
      "items": [{
          "album": {
            "album_type": "album",
            "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            }],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/3yL5ycWxUuHDmclfEWOe5k"
            },
            "href": "https://api.spotify.com/v1/albums/3yL5ycWxUuHDmclfEWOe5k",
            "id": "3yL5ycWxUuHDmclfEWOe5k",
            "images": [{
                "height": 640,
                "url": "https://i.scdn.co/image/9c81b33e2fd24313ef8a4700107e58048f1c225f",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/84fe43951f6119a537104b3a123820a8c5e1d0a7",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/c38f9f2d5e227e629e2513641fd1d1c89a0c1331",
                "width": 64
              }
            ],
            "name": "Sobre Crianças, Quadris, Pesadelos e Lições de Casa...",
            "release_date": "2015-08-07",
            "release_date_precision": "day",
            "total_tracks": 14,
            "type": "album",
            "uri": "spotify:album:3yL5ycWxUuHDmclfEWOe5k"
          },
          "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/57pVvBwa3ZCR9LsVlkLXj7"
              },
              "href": "https://api.spotify.com/v1/artists/57pVvBwa3ZCR9LsVlkLXj7",
              "id": "57pVvBwa3ZCR9LsVlkLXj7",
              "name": "Vanessa Da Mata",
              "type": "artist",
              "uri": "spotify:artist:57pVvBwa3ZCR9LsVlkLXj7"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 221626,
          "explicit": false,
          "external_ids": {
            "isrc": "BRX6F1500010"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/7cnm6MnAwwnf52Jy47WTGN"
          },
          "href": "https://api.spotify.com/v1/tracks/7cnm6MnAwwnf52Jy47WTGN",
          "id": "7cnm6MnAwwnf52Jy47WTGN",
          "is_local": false,
          "name": "Passarinhos (feat. Vanessa Da Mata)",
          "popularity": 58,
          "preview_url": "https://p.scdn.co/mp3-preview/4a09fa6a56f15f624fe5a8aedc75efee5adbd8da?cid=dc6af13b21094058a9b5e104eccee32e",
          "track_number": 7,
          "type": "track",
          "uri": "spotify:track:7cnm6MnAwwnf52Jy47WTGN"
        },
        {
          "album": {
            "album_type": "single",
            "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            }],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/2fChNSVGao2fY5IMggvzWj"
            },
            "href": "https://api.spotify.com/v1/albums/2fChNSVGao2fY5IMggvzWj",
            "id": "2fChNSVGao2fY5IMggvzWj",
            "images": [{
                "height": 640,
                "url": "https://i.scdn.co/image/3d9792c6f34a5c7a1e4e09d1ec3dfb389601fdb2",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/2a9964cdffa529e528ee4eb6849aabbc8c83faa3",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/5f9fc6d4efc35f18773a50f1d47623e288168014",
                "width": 64
              }
            ],
            "name": "Rdio Sessions",
            "release_date": "2016-01-01",
            "release_date_precision": "day",
            "total_tracks": 5,
            "type": "album",
            "uri": "spotify:album:2fChNSVGao2fY5IMggvzWj"
          },
          "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1v0rEJk9ZuCrCQDvCXbO3D"
              },
              "href": "https://api.spotify.com/v1/artists/1v0rEJk9ZuCrCQDvCXbO3D",
              "id": "1v0rEJk9ZuCrCQDvCXbO3D",
              "name": "Xênia França",
              "type": "artist",
              "uri": "spotify:artist:1v0rEJk9ZuCrCQDvCXbO3D"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 229413,
          "explicit": false,
          "external_ids": {
            "isrc": "BRX6F1500024"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/2Oc2oLhrsqADmYYFos8tPt"
          },
          "href": "https://api.spotify.com/v1/tracks/2Oc2oLhrsqADmYYFos8tPt",
          "id": "2Oc2oLhrsqADmYYFos8tPt",
          "is_local": false,
          "name": "Passarinhos (Rdio Sessions) (feat. Xênia França) - Ao Vivo",
          "popularity": 54,
          "preview_url": "https://p.scdn.co/mp3-preview/47a6434e5fd9d3e6d0439d4cf37169db531a062b?cid=dc6af13b21094058a9b5e104eccee32e",
          "track_number": 2,
          "type": "track",
          "uri": "spotify:track:2Oc2oLhrsqADmYYFos8tPt"
        },
        {
          "album": {
            "album_type": "album",
            "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            }],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/3yL5ycWxUuHDmclfEWOe5k"
            },
            "href": "https://api.spotify.com/v1/albums/3yL5ycWxUuHDmclfEWOe5k",
            "id": "3yL5ycWxUuHDmclfEWOe5k",
            "images": [{
                "height": 640,
                "url": "https://i.scdn.co/image/9c81b33e2fd24313ef8a4700107e58048f1c225f",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/84fe43951f6119a537104b3a123820a8c5e1d0a7",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/c38f9f2d5e227e629e2513641fd1d1c89a0c1331",
                "width": 64
              }
            ],
            "name": "Sobre Crianças, Quadris, Pesadelos e Lições de Casa...",
            "release_date": "2015-08-07",
            "release_date_precision": "day",
            "total_tracks": 14,
            "type": "album",
            "uri": "spotify:album:3yL5ycWxUuHDmclfEWOe5k"
          },
          "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/7HGNYPmbDrMkylWqeFCOIQ"
              },
              "href": "https://api.spotify.com/v1/artists/7HGNYPmbDrMkylWqeFCOIQ",
              "id": "7HGNYPmbDrMkylWqeFCOIQ",
              "name": "Caetano Veloso",
              "type": "artist",
              "uri": "spotify:artist:7HGNYPmbDrMkylWqeFCOIQ"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 233320,
          "explicit": false,
          "external_ids": {
            "isrc": "BRX6F1500009"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/7MiSFImFuHFeQqeaSNh9wt"
          },
          "href": "https://api.spotify.com/v1/tracks/7MiSFImFuHFeQqeaSNh9wt",
          "id": "7MiSFImFuHFeQqeaSNh9wt",
          "is_local": false,
          "name": "Baiana (feat. Caetano Veloso)",
          "popularity": 53,
          "preview_url": "https://p.scdn.co/mp3-preview/941e88344a14bb43621b482f5d186b0c3d312d83?cid=dc6af13b21094058a9b5e104eccee32e",
          "track_number": 6,
          "type": "track",
          "uri": "spotify:track:7MiSFImFuHFeQqeaSNh9wt"
        },
        {
          "album": {
            "album_type": "album",
            "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            }],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/57PWjWHzqzODblomXxnQca"
            },
            "href": "https://api.spotify.com/v1/albums/57PWjWHzqzODblomXxnQca",
            "id": "57PWjWHzqzODblomXxnQca",
            "images": [{
                "height": 640,
                "url": "https://i.scdn.co/image/226d75357944551f1d4c991aa1a1a5fbd417712b",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/2162432249dba327a1ad88e0c3fdb24cdbe6641d",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/055db5f06ea48191d0c7244292ffeafdb8f7d35f",
                "width": 64
              }
            ],
            "name": "O Glorioso Retorno de Quem Nunca Esteve Aqui",
            "release_date": "2013",
            "release_date_precision": "year",
            "total_tracks": 14,
            "type": "album",
            "uri": "spotify:album:57PWjWHzqzODblomXxnQca"
          },
          "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0GWNKI3VPEcJsOIEhUjmxd"
              },
              "href": "https://api.spotify.com/v1/artists/0GWNKI3VPEcJsOIEhUjmxd",
              "id": "0GWNKI3VPEcJsOIEhUjmxd",
              "name": "Rael",
              "type": "artist",
              "uri": "spotify:artist:0GWNKI3VPEcJsOIEhUjmxd"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 150439,
          "explicit": false,
          "external_ids": {
            "isrc": "QMBZ91761518"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/0JSux25Te5HYMSr2D64d02"
          },
          "href": "https://api.spotify.com/v1/tracks/0JSux25Te5HYMSr2D64d02",
          "id": "0JSux25Te5HYMSr2D64d02",
          "is_local": false,
          "name": "Levanta e Anda",
          "popularity": 53,
          "preview_url": "https://p.scdn.co/mp3-preview/e8fa6e950037e66fd79c2281b48cbc435f0f4c6e?cid=dc6af13b21094058a9b5e104eccee32e",
          "track_number": 2,
          "type": "track",
          "uri": "spotify:track:0JSux25Te5HYMSr2D64d02"
        },
        {
          "album": {
            "album_type": "album",
            "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            }],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/57PWjWHzqzODblomXxnQca"
            },
            "href": "https://api.spotify.com/v1/albums/57PWjWHzqzODblomXxnQca",
            "id": "57PWjWHzqzODblomXxnQca",
            "images": [{
                "height": 640,
                "url": "https://i.scdn.co/image/226d75357944551f1d4c991aa1a1a5fbd417712b",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/2162432249dba327a1ad88e0c3fdb24cdbe6641d",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/055db5f06ea48191d0c7244292ffeafdb8f7d35f",
                "width": 64
              }
            ],
            "name": "O Glorioso Retorno de Quem Nunca Esteve Aqui",
            "release_date": "2013",
            "release_date_precision": "year",
            "total_tracks": 14,
            "type": "album",
            "uri": "spotify:album:57PWjWHzqzODblomXxnQca"
          },
          "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2dmQ0vMD3THLMcz7DsvfaT"
              },
              "href": "https://api.spotify.com/v1/artists/2dmQ0vMD3THLMcz7DsvfaT",
              "id": "2dmQ0vMD3THLMcz7DsvfaT",
              "name": "Pitty",
              "type": "artist",
              "uri": "spotify:artist:2dmQ0vMD3THLMcz7DsvfaT"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 194194,
          "explicit": false,
          "external_ids": {
            "isrc": "QMBZ91761523"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/2C9LPYpH9YUgROQDHfRXrU"
          },
          "href": "https://api.spotify.com/v1/tracks/2C9LPYpH9YUgROQDHfRXrU",
          "id": "2C9LPYpH9YUgROQDHfRXrU",
          "is_local": false,
          "name": "Hoje Cedo",
          "popularity": 52,
          "preview_url": "https://p.scdn.co/mp3-preview/7090dae5f7c87f5e2d463acdbf8a2c3fcd783250?cid=dc6af13b21094058a9b5e104eccee32e",
          "track_number": 7,
          "type": "track",
          "uri": "spotify:track:2C9LPYpH9YUgROQDHfRXrU"
        },
        {
          "album": {
            "album_type": "compilation",
            "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0LyfQWJT6nXafLPZqxe9Of"
              },
              "href": "https://api.spotify.com/v1/artists/0LyfQWJT6nXafLPZqxe9Of",
              "id": "0LyfQWJT6nXafLPZqxe9Of",
              "name": "Various Artists",
              "type": "artist",
              "uri": "spotify:artist:0LyfQWJT6nXafLPZqxe9Of"
            }],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/4yszZR4HHdWs6JbfE0tpxk"
            },
            "href": "https://api.spotify.com/v1/albums/4yszZR4HHdWs6JbfE0tpxk",
            "id": "4yszZR4HHdWs6JbfE0tpxk",
            "images": [{
                "height": 640,
                "url": "https://i.scdn.co/image/c1ee4663f73354f62a30e6fc093ff8673c44a4b4",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/4019a0f1d7c036f74989077cb7f4262f53b9703b",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/d879f63677261cf6cbdb39b174588440e6ce66e2",
                "width": 64
              }
            ],
            "name": "Sambabook Zeca Pagodinho",
            "release_date": "2014-04-22",
            "release_date_precision": "day",
            "total_tracks": 26,
            "type": "album",
            "uri": "spotify:album:4yszZR4HHdWs6JbfE0tpxk"
          },
          "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/3qZ2n5keOAat1SoF6bHwmb"
              },
              "href": "https://api.spotify.com/v1/artists/3qZ2n5keOAat1SoF6bHwmb",
              "id": "3qZ2n5keOAat1SoF6bHwmb",
              "name": "Zeca Pagodinho",
              "type": "artist",
              "uri": "spotify:artist:3qZ2n5keOAat1SoF6bHwmb"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4vKCAkbdulcqatglgbi5CG"
              },
              "href": "https://api.spotify.com/v1/artists/4vKCAkbdulcqatglgbi5CG",
              "id": "4vKCAkbdulcqatglgbi5CG",
              "name": "Roberta Sá",
              "type": "artist",
              "uri": "spotify:artist:4vKCAkbdulcqatglgbi5CG"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/5JYtpnUKxAzXfHEYpOeeit"
              },
              "href": "https://api.spotify.com/v1/artists/5JYtpnUKxAzXfHEYpOeeit",
              "id": "5JYtpnUKxAzXfHEYpOeeit",
              "name": "Jorge Ben Jor",
              "type": "artist",
              "uri": "spotify:artist:5JYtpnUKxAzXfHEYpOeeit"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/7oEkUINVIj1Nr3Wnj8tzqr"
              },
              "href": "https://api.spotify.com/v1/artists/7oEkUINVIj1Nr3Wnj8tzqr",
              "id": "7oEkUINVIj1Nr3Wnj8tzqr",
              "name": "Gilberto Gil",
              "type": "artist",
              "uri": "spotify:artist:7oEkUINVIj1Nr3Wnj8tzqr"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/57xRtfFlssbpntpRQOBodd"
              },
              "href": "https://api.spotify.com/v1/artists/57xRtfFlssbpntpRQOBodd",
              "id": "57xRtfFlssbpntpRQOBodd",
              "name": "Diogo Nogueira",
              "type": "artist",
              "uri": "spotify:artist:57xRtfFlssbpntpRQOBodd"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4Mw0vJsDXTZF7kn7EsdNoD"
              },
              "href": "https://api.spotify.com/v1/artists/4Mw0vJsDXTZF7kn7EsdNoD",
              "id": "4Mw0vJsDXTZF7kn7EsdNoD",
              "name": "Dudu Nobre",
              "type": "artist",
              "uri": "spotify:artist:4Mw0vJsDXTZF7kn7EsdNoD"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/5GmHrvfki94D20jsW5PRTi"
              },
              "href": "https://api.spotify.com/v1/artists/5GmHrvfki94D20jsW5PRTi",
              "id": "5GmHrvfki94D20jsW5PRTi",
              "name": "Sombrinha",
              "type": "artist",
              "uri": "spotify:artist:5GmHrvfki94D20jsW5PRTi"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/34dfPo3Zi55yM6oV46q4y7"
              },
              "href": "https://api.spotify.com/v1/artists/34dfPo3Zi55yM6oV46q4y7",
              "id": "34dfPo3Zi55yM6oV46q4y7",
              "name": "Mumuzinho",
              "type": "artist",
              "uri": "spotify:artist:34dfPo3Zi55yM6oV46q4y7"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/5rrmaoBXZ7Jcs4Qb77j0YA"
              },
              "href": "https://api.spotify.com/v1/artists/5rrmaoBXZ7Jcs4Qb77j0YA",
              "id": "5rrmaoBXZ7Jcs4Qb77j0YA",
              "name": "Djavan",
              "type": "artist",
              "uri": "spotify:artist:5rrmaoBXZ7Jcs4Qb77j0YA"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1vEN3d3dJbmdHQpXD6AIkL"
              },
              "href": "https://api.spotify.com/v1/artists/1vEN3d3dJbmdHQpXD6AIkL",
              "id": "1vEN3d3dJbmdHQpXD6AIkL",
              "name": "Marcelo D2",
              "type": "artist",
              "uri": "spotify:artist:1vEN3d3dJbmdHQpXD6AIkL"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2bKdKvWKErRrUpSrLsDjyH"
              },
              "href": "https://api.spotify.com/v1/artists/2bKdKvWKErRrUpSrLsDjyH",
              "id": "2bKdKvWKErRrUpSrLsDjyH",
              "name": "Nilze Carvalho",
              "type": "artist",
              "uri": "spotify:artist:2bKdKvWKErRrUpSrLsDjyH"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2cAooeeHKk2UvzUgIxpS0y"
              },
              "href": "https://api.spotify.com/v1/artists/2cAooeeHKk2UvzUgIxpS0y",
              "id": "2cAooeeHKk2UvzUgIxpS0y",
              "name": "Jorge Aragão",
              "type": "artist",
              "uri": "spotify:artist:2cAooeeHKk2UvzUgIxpS0y"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/56TkPi7rpmU8jTpkcK7FY3"
              },
              "href": "https://api.spotify.com/v1/artists/56TkPi7rpmU8jTpkcK7FY3",
              "id": "56TkPi7rpmU8jTpkcK7FY3",
              "name": "Beth Carvalho",
              "type": "artist",
              "uri": "spotify:artist:56TkPi7rpmU8jTpkcK7FY3"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1k8zzgBXqFh30NWvus8cAl"
              },
              "href": "https://api.spotify.com/v1/artists/1k8zzgBXqFh30NWvus8cAl",
              "id": "1k8zzgBXqFh30NWvus8cAl",
              "name": "Rildo Hora",
              "type": "artist",
              "uri": "spotify:artist:1k8zzgBXqFh30NWvus8cAl"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6rM2yY0GnVcOHMU5GD3y9E"
              },
              "href": "https://api.spotify.com/v1/artists/6rM2yY0GnVcOHMU5GD3y9E",
              "id": "6rM2yY0GnVcOHMU5GD3y9E",
              "name": "Martinho Da Vila",
              "type": "artist",
              "uri": "spotify:artist:6rM2yY0GnVcOHMU5GD3y9E"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4YLBdrR3DVSMncm785NH6C"
              },
              "href": "https://api.spotify.com/v1/artists/4YLBdrR3DVSMncm785NH6C",
              "id": "4YLBdrR3DVSMncm785NH6C",
              "name": "Lenine",
              "type": "artist",
              "uri": "spotify:artist:4YLBdrR3DVSMncm785NH6C"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0Aqcba7AHmDUp7UeAQbEDm"
              },
              "href": "https://api.spotify.com/v1/artists/0Aqcba7AHmDUp7UeAQbEDm",
              "id": "0Aqcba7AHmDUp7UeAQbEDm",
              "name": "Monarco",
              "type": "artist",
              "uri": "spotify:artist:0Aqcba7AHmDUp7UeAQbEDm"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/5NZP1TAmVDd3fzmi4X29Jn"
              },
              "href": "https://api.spotify.com/v1/artists/5NZP1TAmVDd3fzmi4X29Jn",
              "id": "5NZP1TAmVDd3fzmi4X29Jn",
              "name": "VELHA GUARDA DA PORTELA",
              "type": "artist",
              "uri": "spotify:artist:5NZP1TAmVDd3fzmi4X29Jn"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2x5fdOl1kpBgD74cOkzNY0"
              },
              "href": "https://api.spotify.com/v1/artists/2x5fdOl1kpBgD74cOkzNY0",
              "id": "2x5fdOl1kpBgD74cOkzNY0",
              "name": "Almir Guineto",
              "type": "artist",
              "uri": "spotify:artist:2x5fdOl1kpBgD74cOkzNY0"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/096an3uS6ZaK2XySae6SqP"
              },
              "href": "https://api.spotify.com/v1/artists/096an3uS6ZaK2XySae6SqP",
              "id": "096an3uS6ZaK2XySae6SqP",
              "name": "Arlindo Cruz",
              "type": "artist",
              "uri": "spotify:artist:096an3uS6ZaK2XySae6SqP"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/3WVjDclrbHsxjxhiOqHdnw"
              },
              "href": "https://api.spotify.com/v1/artists/3WVjDclrbHsxjxhiOqHdnw",
              "id": "3WVjDclrbHsxjxhiOqHdnw",
              "name": "Frejat",
              "type": "artist",
              "uri": "spotify:artist:3WVjDclrbHsxjxhiOqHdnw"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1C8UBSZs5rOPfxuxTMS6OI"
              },
              "href": "https://api.spotify.com/v1/artists/1C8UBSZs5rOPfxuxTMS6OI",
              "id": "1C8UBSZs5rOPfxuxTMS6OI",
              "name": "Maria Rita",
              "type": "artist",
              "uri": "spotify:artist:1C8UBSZs5rOPfxuxTMS6OI"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0hPar6ePAELiu9rYMdvMEo"
              },
              "href": "https://api.spotify.com/v1/artists/0hPar6ePAELiu9rYMdvMEo",
              "id": "0hPar6ePAELiu9rYMdvMEo",
              "name": "Alcione",
              "type": "artist",
              "uri": "spotify:artist:0hPar6ePAELiu9rYMdvMEo"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6gEzJZrbm0F4ihvE9iXR9z"
              },
              "href": "https://api.spotify.com/v1/artists/6gEzJZrbm0F4ihvE9iXR9z",
              "id": "6gEzJZrbm0F4ihvE9iXR9z",
              "name": "Péricles",
              "type": "artist",
              "uri": "spotify:artist:6gEzJZrbm0F4ihvE9iXR9z"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2MaqyTrc7HzuYvLnvfhxIN"
              },
              "href": "https://api.spotify.com/v1/artists/2MaqyTrc7HzuYvLnvfhxIN",
              "id": "2MaqyTrc7HzuYvLnvfhxIN",
              "name": "Mariene De Castro",
              "type": "artist",
              "uri": "spotify:artist:2MaqyTrc7HzuYvLnvfhxIN"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0SkmRxt8o9RTKms28v15MA"
              },
              "href": "https://api.spotify.com/v1/artists/0SkmRxt8o9RTKms28v15MA",
              "id": "0SkmRxt8o9RTKms28v15MA",
              "name": "Gabrielzinho Do Irajá",
              "type": "artist",
              "uri": "spotify:artist:0SkmRxt8o9RTKms28v15MA"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 168893,
          "explicit": false,
          "external_ids": {
            "isrc": "BRUKM1400027"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/6GoFm9E3Nkjve72dwOhmXj"
          },
          "href": "https://api.spotify.com/v1/tracks/6GoFm9E3Nkjve72dwOhmXj",
          "id": "6GoFm9E3Nkjve72dwOhmXj",
          "is_local": false,
          "name": "Camarão Que Dorme A Onda Leva",
          "popularity": 59,
          "preview_url": null,
          "track_number": 25,
          "type": "track",
          "uri": "spotify:track:6GoFm9E3Nkjve72dwOhmXj"
        },
        {
          "album": {
            "album_type": "single",
            "artists": [{
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
                },
                "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
                "id": "2d9LRvQJnAXRijqIJDDs2K",
                "name": "Emicida",
                "type": "artist",
                "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
              },
              {
                "external_urls": {
                  "spotify": "https://open.spotify.com/artist/5xnMjuPp1eDXa8du0SKIHD"
                },
                "href": "https://api.spotify.com/v1/artists/5xnMjuPp1eDXa8du0SKIHD",
                "id": "5xnMjuPp1eDXa8du0SKIHD",
                "name": "Barbatuques",
                "type": "artist",
                "uri": "spotify:artist:5xnMjuPp1eDXa8du0SKIHD"
              }
            ],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/7GKPjR6AqRjOY8G3U2RN7t"
            },
            "href": "https://api.spotify.com/v1/albums/7GKPjR6AqRjOY8G3U2RN7t",
            "id": "7GKPjR6AqRjOY8G3U2RN7t",
            "images": [{
                "height": 640,
                "url": "https://i.scdn.co/image/9bd01261a7deebbc36b9ca74f4e7c26395a9389c",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/4bdc6021a2f443ae3e047aed9db913cd2046d915",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/493a2a8f99f0bd2db0962c435d35db129803f6fe",
                "width": 64
              }
            ],
            "name": "Levanta e Anda",
            "release_date": "2018-10-05",
            "release_date_precision": "day",
            "total_tracks": 1,
            "type": "album",
            "uri": "spotify:album:7GKPjR6AqRjOY8G3U2RN7t"
          },
          "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/5xnMjuPp1eDXa8du0SKIHD"
              },
              "href": "https://api.spotify.com/v1/artists/5xnMjuPp1eDXa8du0SKIHD",
              "id": "5xnMjuPp1eDXa8du0SKIHD",
              "name": "Barbatuques",
              "type": "artist",
              "uri": "spotify:artist:5xnMjuPp1eDXa8du0SKIHD"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 173812,
          "explicit": false,
          "external_ids": {
            "isrc": "BRMPC1800064"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/5fKqHamS4h3bZk6lwvoSxD"
          },
          "href": "https://api.spotify.com/v1/tracks/5fKqHamS4h3bZk6lwvoSxD",
          "id": "5fKqHamS4h3bZk6lwvoSxD",
          "is_local": false,
          "name": "Levanta e Anda",
          "popularity": 48,
          "preview_url": "https://p.scdn.co/mp3-preview/bd30e4c157e3d97ef7d8f83e33988c7501004c2f?cid=dc6af13b21094058a9b5e104eccee32e",
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:5fKqHamS4h3bZk6lwvoSxD"
        },
        {
          "album": {
            "album_type": "single",
            "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0HXL3i1AV3ZRb3BhuzSvOc"
              },
              "href": "https://api.spotify.com/v1/artists/0HXL3i1AV3ZRb3BhuzSvOc",
              "id": "0HXL3i1AV3ZRb3BhuzSvOc",
              "name": "Devasto Prod",
              "type": "artist",
              "uri": "spotify:artist:0HXL3i1AV3ZRb3BhuzSvOc"
            }],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/1hY230xXMYPnMDAWLASSV2"
            },
            "href": "https://api.spotify.com/v1/albums/1hY230xXMYPnMDAWLASSV2",
            "id": "1hY230xXMYPnMDAWLASSV2",
            "images": [{
                "height": 640,
                "url": "https://i.scdn.co/image/1c405d8c08c7d0a9f9bf1a4ee5940575aae5dfee",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/7cf7fdcd03ce066eca491fa8ade17164c3bff033",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/729bf3fcf4ba0fd4bb68af6e29c4e7cac944b850",
                "width": 64
              }
            ],
            "name": "O Céu É o Limite",
            "release_date": "2018-10-12",
            "release_date_precision": "day",
            "total_tracks": 1,
            "type": "album",
            "uri": "spotify:album:1hY230xXMYPnMDAWLASSV2"
          },
          "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0HXL3i1AV3ZRb3BhuzSvOc"
              },
              "href": "https://api.spotify.com/v1/artists/0HXL3i1AV3ZRb3BhuzSvOc",
              "id": "0HXL3i1AV3ZRb3BhuzSvOc",
              "name": "Devasto Prod",
              "type": "artist",
              "uri": "spotify:artist:0HXL3i1AV3ZRb3BhuzSvOc"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6syQjkQSMIrzw5cFnNRheo"
              },
              "href": "https://api.spotify.com/v1/artists/6syQjkQSMIrzw5cFnNRheo",
              "id": "6syQjkQSMIrzw5cFnNRheo",
              "name": "Rincon Sapiência",
              "type": "artist",
              "uri": "spotify:artist:6syQjkQSMIrzw5cFnNRheo"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1YOVBTvznjiDvtAj4ExHeo"
              },
              "href": "https://api.spotify.com/v1/artists/1YOVBTvznjiDvtAj4ExHeo",
              "id": "1YOVBTvznjiDvtAj4ExHeo",
              "name": "BK",
              "type": "artist",
              "uri": "spotify:artist:1YOVBTvznjiDvtAj4ExHeo"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0GWNKI3VPEcJsOIEhUjmxd"
              },
              "href": "https://api.spotify.com/v1/artists/0GWNKI3VPEcJsOIEhUjmxd",
              "id": "0GWNKI3VPEcJsOIEhUjmxd",
              "name": "Rael",
              "type": "artist",
              "uri": "spotify:artist:0GWNKI3VPEcJsOIEhUjmxd"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/204IwDdaHE4ymGk9Kya2pY"
              },
              "href": "https://api.spotify.com/v1/artists/204IwDdaHE4ymGk9Kya2pY",
              "id": "204IwDdaHE4ymGk9Kya2pY",
              "name": "Djonga",
              "type": "artist",
              "uri": "spotify:artist:204IwDdaHE4ymGk9Kya2pY"
            },
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0fMjaafeNhHPA6mJ5ZglAJ"
              },
              "href": "https://api.spotify.com/v1/artists/0fMjaafeNhHPA6mJ5ZglAJ",
              "id": "0fMjaafeNhHPA6mJ5ZglAJ",
              "name": "Mano Brown",
              "type": "artist",
              "uri": "spotify:artist:0fMjaafeNhHPA6mJ5ZglAJ"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 341684,
          "explicit": false,
          "external_ids": {
            "isrc": "QZ5AB2079546"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/1iDARoNb186UAnHvZ6w0gv"
          },
          "href": "https://api.spotify.com/v1/tracks/1iDARoNb186UAnHvZ6w0gv",
          "id": "1iDARoNb186UAnHvZ6w0gv",
          "is_local": false,
          "name": "O Céu É o Limite",
          "popularity": 52,
          "preview_url": "https://p.scdn.co/mp3-preview/10e9a1b2475e6267c6bb3fca0c2a1146fe7776dd?cid=dc6af13b21094058a9b5e104eccee32e",
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:1iDARoNb186UAnHvZ6w0gv"
        },
        {
          "album": {
            "album_type": "single",
            "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            }],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/3ZOEkaADwSaa8zJGofKdPh"
            },
            "href": "https://api.spotify.com/v1/albums/3ZOEkaADwSaa8zJGofKdPh",
            "id": "3ZOEkaADwSaa8zJGofKdPh",
            "images": [{
                "height": 640,
                "url": "https://i.scdn.co/image/7742e5f4220b66c9c41b059113300c27a0d684b8",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/cfbb8ebb5859f5138d8146002785792ecd35ac30",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/fb115743c644a93db8307d7f82e9ca44e753c508",
                "width": 64
              }
            ],
            "name": "Pantera Negra",
            "release_date": "2018-02-02",
            "release_date_precision": "day",
            "total_tracks": 1,
            "type": "album",
            "uri": "spotify:album:3ZOEkaADwSaa8zJGofKdPh"
          },
          "artists": [{
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
            },
            "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
            "id": "2d9LRvQJnAXRijqIJDDs2K",
            "name": "Emicida",
            "type": "artist",
            "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
          }],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 199613,
          "explicit": false,
          "external_ids": {
            "isrc": "BRX6F1800001"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/6T9YY1XmfjiqpRZFl7OmYq"
          },
          "href": "https://api.spotify.com/v1/tracks/6T9YY1XmfjiqpRZFl7OmYq",
          "id": "6T9YY1XmfjiqpRZFl7OmYq",
          "is_local": false,
          "name": "Pantera Negra",
          "popularity": 48,
          "preview_url": "https://p.scdn.co/mp3-preview/9055e83f388839779fc249e4e58bf07bc2706de1?cid=dc6af13b21094058a9b5e104eccee32e",
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:6T9YY1XmfjiqpRZFl7OmYq"
        },
        {
          "album": {
            "album_type": "single",
            "artists": [{
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
              },
              "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
              "id": "2d9LRvQJnAXRijqIJDDs2K",
              "name": "Emicida",
              "type": "artist",
              "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
            }],
            "available_markets": [
              "AD",
              "AE",
              "AR",
              "AT",
              "AU",
              "BE",
              "BG",
              "BH",
              "BO",
              "BR",
              "CA",
              "CH",
              "CL",
              "CO",
              "CR",
              "CY",
              "CZ",
              "DE",
              "DK",
              "DO",
              "DZ",
              "EC",
              "EE",
              "EG",
              "ES",
              "FI",
              "FR",
              "GB",
              "GR",
              "GT",
              "HK",
              "HN",
              "HU",
              "ID",
              "IE",
              "IL",
              "IS",
              "IT",
              "JO",
              "JP",
              "KW",
              "LB",
              "LI",
              "LT",
              "LU",
              "LV",
              "MA",
              "MC",
              "MT",
              "MX",
              "MY",
              "NI",
              "NL",
              "NO",
              "NZ",
              "OM",
              "PA",
              "PE",
              "PH",
              "PL",
              "PS",
              "PT",
              "PY",
              "QA",
              "RO",
              "SA",
              "SE",
              "SG",
              "SK",
              "SV",
              "TH",
              "TN",
              "TR",
              "TW",
              "US",
              "UY",
              "VN",
              "ZA"
            ],
            "external_urls": {
              "spotify": "https://open.spotify.com/album/5Da4i51D8HPrIdyqVLE916"
            },
            "href": "https://api.spotify.com/v1/albums/5Da4i51D8HPrIdyqVLE916",
            "id": "5Da4i51D8HPrIdyqVLE916",
            "images": [{
                "height": 640,
                "url": "https://i.scdn.co/image/8b507993a0213660343e03fff1b25e33f43e609e",
                "width": 640
              },
              {
                "height": 300,
                "url": "https://i.scdn.co/image/8c2eda19b3538e37ede0a48a0b8d0458447e4bf2",
                "width": 300
              },
              {
                "height": 64,
                "url": "https://i.scdn.co/image/d475e06ae66c2bde8359d4f443f5877755fc74e2",
                "width": 64
              }
            ],
            "name": "Inácio da Catingueira",
            "release_date": "2018-09-18",
            "release_date_precision": "day",
            "total_tracks": 1,
            "type": "album",
            "uri": "spotify:album:5Da4i51D8HPrIdyqVLE916"
          },
          "artists": [{
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2d9LRvQJnAXRijqIJDDs2K"
            },
            "href": "https://api.spotify.com/v1/artists/2d9LRvQJnAXRijqIJDDs2K",
            "id": "2d9LRvQJnAXRijqIJDDs2K",
            "name": "Emicida",
            "type": "artist",
            "uri": "spotify:artist:2d9LRvQJnAXRijqIJDDs2K"
          }],
          "available_markets": [
            "AD",
            "AE",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BH",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JO",
            "JP",
            "KW",
            "LB",
            "LI",
            "LT",
            "LU",
            "LV",
            "MA",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PH",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "SA",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TN",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "disc_number": 1,
          "duration_ms": 235413,
          "explicit": true,
          "external_ids": {
            "isrc": "BRX6F1800072"
          },
          "external_urls": {
            "spotify": "https://open.spotify.com/track/6jqt08nh1lKvT4JBxwLAS6"
          },
          "href": "https://api.spotify.com/v1/tracks/6jqt08nh1lKvT4JBxwLAS6",
          "id": "6jqt08nh1lKvT4JBxwLAS6",
          "is_local": false,
          "name": "Inácio da Catingueira",
          "popularity": 47,
          "preview_url": "https://p.scdn.co/mp3-preview/7c869486461265bd7e1d3713ff817dd064ee831e?cid=dc6af13b21094058a9b5e104eccee32e",
          "track_number": 1,
          "type": "track",
          "uri": "spotify:track:6jqt08nh1lKvT4JBxwLAS6"
        }
      ],
      "limit": 10,
      "next": "https://api.spotify.com/v1/search?query=emicida&type=track&market=BR&offset=10&limit=10",
      "offset": 0,
      "previous": null,
      "total": 366
    }
  },
  "status": 200,
  "statusText": "",
  "headers": {
    "content-type": "application/json; charset=utf-8",
    "cache-control": "public, max-age=7200"
  },
  "config": {
    "transformRequest": {},
    "transformResponse": {},
    "timeout": 0,
    "xsrfCookieName": "XSRF-TOKEN",
    "xsrfHeaderName": "X-XSRF-TOKEN",
    "maxContentLength": -1,
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Authorization": "Bearer BQDCScmlhQYHETTUU10FcxuMvrTg40XQ1JSO3-4UVSINkO7vaTBLNT6W8CKgScZPbWvYzPssdbwBflHZizZU-XVgrutA70IKVDBWFRcktf3a4H8xggmD5UVjgatKZHNsd0pGKA_eYNRvHLzvTexSEVIjf5Nkd3lVsuHaZaBNNatSHb7hQjuoTRQ8AbIJ5sM"
    },
    "method": "get",
    "url": "https://api.spotify.com/v1/search?q=emicida&type=track%2Cartist&limit=10"
  },
  "request": {}
}
export default searchList;